from app.models.ai_recommendations import AIRecommendation
from app.models.document_versions import DocumentVersion
from app.models.documents import Document
from app.models.knowledge_chunks import KnowledgeChunk
from app.models.knowledge_documents import KnowledgeDocument
from app.models.memory_entries import MemoryEntry
from app.models.message_history import MessageHistory
from app.models.projects import Project
from app.models.proactive_rules import ProactiveRule
from app.models.risks import Risk
from app.models.tasks import Task
from app.models.users import User
